services:
  - postgresql
  - xvfb

environment:
  global:
    POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6
    PGUSER: postgres
    #PGPASSWORD: postgres

  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "32"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PATH=%POSTGRES_PATH%\\bin;%PATH%"
  - "python --version"
  #- pip install --upgrade pip
  #- pip install -r requirements.txt
  #- pip install -r test-requirements.txt

build_script:
  #- psql postgres://postgres:postgres@localhost:5432 -c 'create database mercury;'
  #- psql postgres://postgres:@localhost:5432 -c 'create database mercury;'
  - touch ~/.pgpass
  - echo "localhost:5432:mercury:postgres:postgres" >> ~/.pgpass
  - psql -c "create database mercury;" -U postgres
  #- psql -c 'create database mercury;'
  - echo "finished executing psql -c 'create database mercury;"
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - black --check --diff .
  - flake8 .
  - coverage run manage.py test

after_test:
  - coveralls
  - cat geckodriver.log
