services:
  - postgresql
  - xvfb

environment:
  global:
    POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6

  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PATH=%POSTGRES_PATH%\\bin;%PATH%"
  #- createdb "mercury"
  - "python --version"
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

build_script:
  #- sh scripts/appveyor.sh
  - psql -c 'create database mercury;'
  - python3 manage.py migrate
  - python3 manage.py collectstatic --noinput
  - black --check --diff .
  - flake8 .
  - coverage run manage.py test

after_test:
  - coveralls
  - cat geckodriver.log
