environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

services:
  - postgresql
  - xvfb

before_build:

install:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  #- "SET PATH=%POSTGRES_PATH%\\bin;%MYSQL_PATH%\\bin;%PATH%"
  - "python --version"
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

build_script:
  - black --check --diff .
  - flake8 .
  - coverage run manage.py test

after_test:
  - coveralls
  - cat geckodriver.log
