version: '3.2'

services:
    com:
        build:
            context: .
            dockerfile: Dockerfile
            
    sense:
        build:
            context: .
            dockerfile: Dockerfile
            cache_from: 
                - nyumotorsportstelemetryorg/mercury
            # args:
            #     - HARDWARE_TYPE=sensePi
            #     - LAN_SERVER_IP=com
            #     - USE_GPS=False
        environment: 
            - HARDWARE_TYPE=sensePi
            - LAN_SERVER_IP=com
            - USE_GPS=False
        depends_on: 
            - com
        volumes:
            # - "/Users/alexbiehl/dev/serial0:/dev/serial0"
            - "/dev/serial0:/dev/serial0"