version: '3'

services:
    com:
        build:
            context: .
            dockerfile: Dockerfile
            
    sense:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PI_TYPE=sensePI
                - LAN_SERVER_IP=com
        environment: 
            - PI_TYPE=sensePI
            - LAN_SERVER_IP=com
        depends_on: 
            - com
        volumes:
            # - "/Users/alexbiehl/dev/serial0:/dev/serial0"
            - "/dev/serial0:/dev/serial0"